# Generated by Django 4.2.7 on 2023-11-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
