version: '3.8'

volumes:
  postgres_data:

services:
  app:
    build: 
      context: .
    image: what-test
    container_name: what-test-container
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    ports:
      - "8000:80"
    working_dir: /app
    volumes:
      - ".:/app:rw"
    env_file:
      - ./.env-local
    depends_on:
      database_default:
        condition: service_healthy

  database_default:
    # the application's web service will use an off-the-shelf image
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
    container_name: whattest-postgres-container
    ports:
      - "5432:5432"
    volumes:
      - ".:/app:rw"
    healthcheck:
      # This command checks if the database is ready, right on the source db server
      test: "pg_isready -d postgres -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5